version: '2'
services:
    myapp-app:
        image: myapp
        external_links:
            - myapp-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/myapp?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    myapp-mysql:
        extends:
            file: mysql.yml
            service: myapp-mysql
